# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1khwqSoa5juZdcfVDqGLLmqOgv385UZqY
"""

import streamlit as st
import numpy as np
import joblib

# Load the model
model = joblib.load('model.pkl')

st.title('Loan Price Prediction')

# Input fields
loan_amount = st.number_input('Loan Amount:', value=0.0)
credit_score = st.number_input('Credit Score:', value=0.0)
cpi = st.number_input('CPI:', value=0.0)
unemployment_rate = st.number_input('Unemployment Rate:', value=0.0)
treasury_rate = st.number_input('Treasury Rate:', value=0.0)
income = st.number_input('Income:', value=0.0)

if st.button('Predict'):
    # Prepare the input array
    input_data = np.array([[unemployment_rate, cpi, treasury_rate, loan_amount, credit_score, income]])

    # Make prediction
    prediction = model.predict(input_data)[0]

    st.success(f'Predicted Loan Price: ${prediction:.2f}')